name: Detect new package

on:
  registry_package:
#    tags:
#      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
