name: Get tag

on:
  workflow_run:
    workflows: [Cleanup branch]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The image tag. E.g. 0.5.0"

run-name: ${{ github.workflow }} - ${{ github.event_name == 'workflow_dispatch' && inputs.tag && format('v{0}', inputs.tag) || github.event_name == 'workflow_run' && 'latest' || '' }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get latest or selected tag
        id: get-tag
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          git fetch -f --all --tags
          export input_tag=${{ inputs.tag }}
          if [ -z "${input_tag}" ]; then
            echo "TAG=${input_tag}"
          else
            # Get the latest tag
            echo "TAG=$(git tag --list | grep -E "^[0-9]+.[0-9]+.[0-9]+" | sort -V | tail -n1)"
          fi
